### PR TITLE
Add Tado AIR_CONDITIONING sensor

### PR DESCRIPTION
**Pull request by Yippy**
## Description:
Added the essential sensors from AC
visual

ac_sensor

AC mode with 'COOL' has seperate 'COOL' option.
ac_cool_mode

Requires changes to PyTado to correctly send the required AC API call
https://github.com/wmalgadey/PyTado/commit/5925c9f8b9e50648b8d9ad2bf0810c51bd4a98f3
~~chrism0dwk/PyTado#5~~

Will Resolve
wmalgadey/tado_component#23
home-assistant/home-assistant#6943

## Checklist:
  - [ ] Ensure the latest PyTado 0.2.6 is loaded (IMPORTANT)
  - [x] Fix controlling AC climate API (@wmalgadey has already worked on it via his own PyTado branch)
  - [x] Added AC sensors
  - [x] Fix AC operation mode, 'HEAT' and 'COOL', 'COOL' or 'HEAT' is supported
  - [ ] Fix HOT_WATER without that has false canSetTemperature, cannot test as I don't have HOT_WATER
  - [x] To control climate, API requires extra parameters that are found the updated PyTado (v2.5 https://github.com/wmalgadey/PyTado/commit/5925c9f8b9e50648b8d9ad2bf0810c51bd4a98f3  ~~chrism0dwk/PyTado#5~~)

### CODE REVIEW

**Comment by Yippy** [comment]
@wmalgadey 
This pull request is almost done but I cannot test the API calls for your newer PyTado 0.2.5 release,
how to I force import of the PyTado 0.2.5?

The extra parameters for calling setZoneOverlay with device_type, power, ac_mode makes an exception.
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/service.py", line 224, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/climate/tado.py", line 234, in set_operation_mode
    self._control_heating()
  File "/config/custom_components/climate/tado.py", line 365, in _control_heating
    self._store.set_zone_overlay(self.zone_id, self.device_type, CONST_OVERLAY_MANUAL)
  File "/config/custom_components/tado.py", line 137, in set_zone_overlay
    self.tado.setZoneOverlay(zone_id, overlay_mode, temperature, duration, device_type, power, ac_mode)
TypeError: setZoneOverlay() takes from 3 to 6 positional arguments but 8 were given
```

I've tried setting the requirement to the ZIP
```
REQUIREMENTS = ['https://github.com/wmalgadey/PyTado/archive/'
                '0.2.5.zip#'
                'PyTado==0.2.5']
```
Error
```
Unable to install package https://github.com/wmalgadey/PyTado/archive/0.2.5.zip#PyTado==0.2.5: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-z6njd25p/
```

**Comment by thieaux** [comment]
Thanks let me give it shot!!! ill report back

**Comment by wmalgadey** [comment]
I created a new pyTado version (0.2.6) and uploaded it to pypi.org. It has the fix from yippy included.

**Comment by Yippy** [comment]
@thieaux @wmalgadey 
The API now works for 'HEAT' and 'COOL' modes, Heating and AC can now set the climate operation mode correctly.

The only thing I've notice that the duration of the TIMER or TADO_MODE is not used.

Also getting the PyTado 0.2.6 still does not work, I've tried
```
REQUIREMENTS = ['python-tado==0.2.6']
```
and
```
REQUIREMENTS = ['PyTado==0.2.6']
```

Not sure why it doesn't work, but I've manually added /deps/lib/python3.6/site-packages/PyTado/ to test the API.

HOT WATER with canSetTemperature as false would not be generated as a device, judging by the code.

**Comment by wmalgadey** [comment]
> REQUIREMENTS = ['PyTado==0.2.6']

this should be the right one. You have to add that to requirements.txt too, if I remember correct.

**Comment by thieaux** [comment]
Sorry @wmalgadey @Yippy:
Been swamp with a new installation, tonight ill give it a go.... i thought i was running hassbian this things is docker, let me get my bearings so i can tackle it ...
 if i remember correctly custom_components supersedes the config.yaml right?

**Comment by Yippy** [comment]
@thieaux I'm using docker, just do the following add the files into this structure
/config/custom_components/tado.py
/config/custom_components/climate/tado.py
/config/custom_components/sensor/tado.py

I haven't got the PyTado 0.2.6 to work, you have to remove requirements. Add the PyTado 0.2.6 manually into 
/config/deps/lib/python3.6/site-packages/PyTado/

interface.py
__main__.py
__inin__.py

**Comment by thieaux** [comment]
pi is not letting me log into host. keeps refusing 22222....

**Comment by thieaux** [comment]
> @thieaux I'm using docker, just do the following add the files into this structure
> /config/custom_components/tado.py
> /config/custom_components/climate/tado.py
> /config/custom_components/sensor/tado.py
> 
> I haven't got the PyTado 0.2.6 to work, you have to remove requirements. Add the PyTado 0.2.6 manually into
> /config/deps/lib/python3.6/site-packages/PyTado/
> 
> interface.py
> **main**.py
> **inin**.py

Keep getting the same errors..... 
Can you post your tado.py?

**Comment by Yippy** [comment]
@thieaux 
You meant to use the changes I've made within this pull request:

/config/custom_components/tado.py
https://github.com/wmalgadey/home-assistant/blob/d85733b53b517d1d79767822778da6e4bb1efbf2/homeassistant/components/tado.py

/config/custom_components/climate/tado.py
https://github.com/wmalgadey/home-assistant/blob/d85733b53b517d1d79767822778da6e4bb1efbf2/homeassistant/components/climate/tado.py

/config/custom_components/sensor/tado.py
https://github.com/wmalgadey/home-assistant/blob/d85733b53b517d1d79767822778da6e4bb1efbf2/homeassistant/components/sensor/tado.py

Remove requirements from line 18
Then add the 0.2..6 https://github.com/wmalgadey/PyTado/releases/tag/0.2.6 manually into this structure:

/config/deps/lib/python3.6/site-packages/PyTado/
you only need the following files in that folder:
```
__init__.py
interface.py
__main__.py
```

I can't help you beyond that I know.

@wmalgadey I'm not sure if I need to do any more changes? I can't really test the whole home-assistant

**Comment by thieaux** [comment]
@Yippy @wmalgadey Sorry mates, i was exhausted and not thinking straight i got to play a little bit today before heading out and got it working sort of, tonight ill give it a go, but seems to be reporting fine....

@Yippy thanks for the patience and your contribution
@wmalgadey excellent job

**Comment by Yippy** [comment]
@thieaux
Thanks glad it's all working, at least it was tested.

@wmalgadey I think this is ready to be merge

**Comment by thieaux** [comment]
@Yippy @wmalgadey 
Quick question, everything is reporting fine and updating when i call from the mytado, but i f i call a services  from the HA i get
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 224, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/climate/tado.py", line 287, in set_operation_mode
    self._control_heating()
  File "/config/custom_components/climate/tado.py", line 423, in _control_heating
    self.zone_id, self._device_type, self._current_operation, self._target_temp, None, self._mode, self._device_is_active)
  File "/config/custom_components/tado.py", line 135, in set_zone_overlay
    self.tado.setZoneOverlay(zone_id, overlay_mode, temperature, duration, device_type, power, mode)
TypeError: setZoneOverlay() takes from 3 to 5 positional arguments but 8 were given
```

**Comment by wmalgadey** [comment]
this seems like an error with wrong pyTado lib, because we added more parameters in 0.2.6.

We can merge the changes from yippy (thanks again for your work here, great job 👍). There may be some more issues, when we integrate it into the main hass repository.

**Comment by thieaux** [comment]
> this seems like an error with wrong pyTado lib, because we added more parameters in 0.2.6.
> 
> We can merge the changes from yippy (thanks again for your work here, great job 👍). There may be some more issues, when we integrate it into the main hass repository.

Did quick check, i had mess with the @Yippy pulls, in some places had the old ones and others the new, but i can say with confidence that is 100% working at least for what i've tried...

Excellent Job Mates @Yippy and @wmalgadey ,

**Comment by thieaux** [comment]
@Yippy @wmalgadey  i dont know if you noticed but mine, would not hold the temperatue if iset it to 22c in ha, tado shows 22c but the ac will defaut to 17

**Comment by Yippy** [comment]
@thieaux there are two temperature modes, HEAT or COOL does your AC support one or the other or both?

If the temperature is out of bound of COOL it probably ignore the temperature. Let me know what setup and operating mode. Example Manual (Cool) or Manual

**Comment by thieaux** [comment]
> @thieaux there are two temperature modes, HEAT or COOL does your AC support one or the other or both?
> 
> If the temperature is out of bound of COOL it probably ignore the temperature. Let me know what setup and operating mode. Example Manual (Cool) or Manual

@Yippy Manual Cool @22 degrees C just a Cooling Unit, one thing though when i try to set the temperature in Ha i get floating point numbers not [integers....](https://imgur.com/a/63mpzdf) link to screen shot

@Yippy  Don't worry about it, i am 100% sure this has nothing to do with HA and Pytado...but between my Ac and the tado, my unit was not listed in the database so it had to learn the code from the remote, i was jut putting it out there in case someone ran into the same issue...i am going to try it on another unit i have that is on the tado database and report back..

**Comment by thieaux** [comment]
I suspect the temp issue is with the tado api itself, setting up the other A/C there is an option for a Non-thermostatic control, where the tado overrides the a/c remotes for temperature settings, i'm going to fiddle with it a bit and let you guys know, my pi decided to kill itself so im starting again from scratch

**Comment by thieaux** [comment]
@wmalgadey @Yippy reconfigured the tado as non-thermostatic unit, but still getting the same errors when i call a service from HA..

`2018-11-01 22:43:53 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 224, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/climate/tado.py", line 287, in set_operation_mode
    self._control_heating()
  File "/config/custom_components/climate/tado.py", line 415, in _control_heating
    self._store.set_zone_overlay(self.zone_id, self._device_type, CONST_OVERLAY_MANUAL)
  File "/config/custom_components/tado.py", line 135, in set_zone_overlay
    self.tado.setZoneOverlay(zone_id, overlay_mode, temperature, duration, device_type, power, mode)
TypeError: setZoneOverlay() takes from 3 to 5 positional arguments but 8 were given`

**Comment by thieaux** [comment]
> @thieaux the API error is down to using the old PyTado v0.2.4, the new PyTado v0.2.6 will make it work. I've tested the new PyTado v0.2.6 and it seems to be working, I'm not sure how to force the installation to use the latest version without overriding it.
> 
> Check my previous comment to see how to override the old PyTado.

 its overridden im using  0.2.6 Alpha....
well it was worth a shot, for the time being ill keep using my mobile, thanks anyways guys.... excellent job!!!!!

**Comment by thieaux** [comment]
@Yippy @wmalgadey 
So i went ahead and use iframes, to fetch the front end of mytado, i know is  not the most elegant solution but for the time being it works...just wanted to let you know....

Again thanks for the patience and help

**Comment by rafuz** [comment]
Seems that with hass 0.89. this component does not load anymore. It complains about missing dependencies.

**Comment by wmalgadey** [comment]
that doesn't seem like a general problem. I am using HassOS 2.10 and did the update to 0.89. My tado component loads like expected

**Pull request merged**
